
import "./globals.css";
import "./style.css";
import "./custom.css";

export const metadata = {
  title: "CEPI - Blog",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>{children}</body>

    </html>
  );
}
